# -------------------------------------------------------------------
# Authors: Hye Chan Lee (hl63@calvin.edu), Clive Amoh (csa25@calvin.edu)
# File: smart_door.py
# Course: CS326 - Embedded Systems
# Description: Main script for smart door system with face recognition,
#              motion detection, MQTT communication, LED control,
#              and servo control.
# Date: May 2025
# -------------------------------------------------------------------

import pigpio
import paho.mqtt.client as mqtt
import time
from datetime import datetime
import os
import cv2
import face_recognition
import pickle
import numpy as np
from imutils import paths
from gpiozero import MotionSensor, Button
from picamera2 import Picamera2
import threading

# GPIO Pins
LOCK_SERVO = 18
DOOR_SERVO = 17
GREEN_LED = 23
RED_LED = 24
YELLOW_LED = 27
IR_SENSOR = 25
CONFIRM_BUTTON_PIN = 22

# MQTT Settings
BROKER = "iot.cs.calvin.edu"
PORT = 1883
TOPIC_CONTROL = "hl63/door_control"
TOPIC_STATUS = "hl63/door_status"
TOPIC_ALERT = "hl63/door_alert"

USERNAME = ""  # Input the broker username
PASSWORD = ""  # Input the broker password

# Initialize pigpio
pi = pigpio.pi()
if not pi.connected:
    print("Could not connect to pigpio daemon.")
    exit()

# Set up LEDs and motion sensor
pi.set_mode(GREEN_LED, pigpio.OUTPUT)
pi.set_mode(RED_LED, pigpio.OUTPUT)
pi.set_mode(YELLOW_LED, pigpio.OUTPUT)
motion = MotionSensor(IR_SENSOR)
confirm_button = Button(CONFIRM_BUTTON_PIN, pull_up=False)

# Face storage directories
DATASET_DIR = "dataset"
os.makedirs(DATASET_DIR, exist_ok=True)

# Constants for slow servo control
DEFAULT_STEP_SIZE = 10
DEFAULT_DELAY = 0.02
SERVO_MIN_PULSE = 1000  # Minimum pulse width for servo
SERVO_MAX_PULSE = 2000  # Maximum pulse width for servo


class SmartDoor:
    def __init__(self, pi):
        """
        Initialize the SmartDoor object with the pigpio instance.

        Args:
            pi (pigpio.pi): The pigpio instance for GPIO control.
        """
        # Initialize the SmartDoor object with the pigpio instance
        self.pi = pi
        self.suppress_motion_detection = False  # Flag to suppress motion detection
        self.training_session_active = False  # Flag to indicate if training is active
        self.awaiting_training_name = None  # Name awaiting confirmation for training
        self.locked = True  # Door starts in a locked state
        self.known_encodings = []  # List of known face encodings
        self.known_names = []  # List of known names corresponding to encodings
        self.load_known_faces()  # Load known faces from storage
        self.lock()  # Lock the door initially
        confirm_button.when_pressed = self.handle_button_press  # Set up button press handler

    def lock(self):
        """
        Lock the door by controlling the lock servo and updating the LED indicators.
        """
        print("[INFO] Locking the door...")
        # Move servo to locked position
        self.pi.set_servo_pulsewidth(LOCK_SERVO, 1000)
        time.sleep(1)  # Allow time for servo to move
        self.pi.set_servo_pulsewidth(LOCK_SERVO, 0)  # Stop servo
        self.locked = True  # Update locked state
        self.pi.write(RED_LED, 1)
        self.pi.write(GREEN_LED, 0)
        client.publish(TOPIC_STATUS, "Door closed and locked.")

    def unlock(self):
        """
        Unlock the door by controlling the lock servo and updating the LED indicators.
        """
        print("[INFO] Unlocking the door...")
        # Move servo to unlocked position
        self.pi.set_servo_pulsewidth(LOCK_SERVO, 2000)
        time.sleep(1)  # Allow time for servo to move
        self.pi.set_servo_pulsewidth(LOCK_SERVO, 0)  # Stop servo
        self.locked = False  # Update locked state
        self.pi.write(RED_LED, 0)
        self.pi.write(GREEN_LED, 1)

    def slowly_move_servo(self, pin, start, end, step=DEFAULT_STEP_SIZE, delay=DEFAULT_DELAY):
        """
        Sweep the servo motor between two positions.

        Args:
            pin (int): GPIO pin connected to the servo.
            start (int): Starting pulse width for the servo.
            end (int): Ending pulse width for the servo.
            step (int, optional): Step size for sweeping. Defaults to DEFAULT_STEP_SIZE.
            delay (float, optional): Delay between steps in seconds. Defaults to DEFAULT_DELAY.
        """
        # Code generated by Copilot, modified for clarity and functionality

        if start < end:
            # Incrementally move servo from start to end position
            for pw in range(start, end + 1, step):
                self.pi.set_servo_pulsewidth(pin, pw)
                time.sleep(delay)
        else:
            # Incrementally move servo from end to start position
            for pw in range(start, end - 1, -step):
                self.pi.set_servo_pulsewidth(pin, pw)
                time.sleep(delay)
        self.pi.set_servo_pulsewidth(pin, 0)  # Stop servo after sweeping

    def sweep_servo(self):
        """
        Open the door by sweeping the door servo to the open position.
        """
        print("[INFO] Opening the door...")
        # Sweep servo to open position
        self.slowly_move_servo(DOOR_SERVO, SERVO_MIN_PULSE, SERVO_MAX_PULSE)

    def close_door(self):
        """
        Close the door by sweeping the door servo to the closed position.
        """
        print("[INFO] Closing the door...")
        # Sweep servo to closed position
        self.slowly_move_servo(DOOR_SERVO, 2000, 1000)

    def handle_door_opening(self):
        """
        Handle the process of unlocking, opening, and closing the door.
        Temporarily disables motion detection during the process.
        """
        self.suppress_motion_detection = True  # Temporarily disable motion detection
        self.unlock()  # Unlock the door
        self.sweep_servo()  # Open the door
        print("[INFO] Waiting for motion to stop before closing the door...")
        # Wait until no motion is detected before closing the door
        while motion.motion_detected:
            time.sleep(1)
        self.close_door()
        self.lock()
        print("[INFO] Door closed and locked. Resuming motion detection.")
        client.publish(TOPIC_STATUS, "Door closed and locked.")
        self.suppress_motion_detection = False  # Re-enable motion detection

    def handle_button_press(self):
        """
        Handle the button press event for initiating face registration.
        Notifies via MQTT and disables motion detection during the process.
        """
        if self.training_session_active:
            print("[INFO] Training already in progress. Ignoring button press.")
            return

        # Set up for a new training session
        self.awaiting_training_name = "new_user"
        # Disable motion detection during training
        self.suppress_motion_detection = True
        print(
            "[INFO] Button pressed. Waiting for confirmation from app to train as new_user."
        )
        # Notify via MQTT that a new face registration is requested
        client.publish(
            TOPIC_ALERT,
            "Button pressed. Send 'Confirm face register' to register face as new_user.",
        )

    def load_known_faces(self):
        """
        Load known face encodings and names from a pickle file.
        If the file does not exist, prints a warning message.
        """
        # Refereced and modified accordingly from YouTube video:
        # "Facial Recognition for Raspberry Pi with OpenCV and Python" by Core Electronics,
        # URL: https://www.youtube.com/watch?v=3TUlJrRJUeM, retrieved on 2025-04-01

        if not os.path.exists("encodings.pickle"):
            print("No encodings file found.")
            return
        # Load encodings and names from the pickle file
        with open("encodings.pickle", "rb") as f:
            data = pickle.loads(f.read())
            self.known_encodings = data["encodings"]
            self.known_names = data["names"]
        print(f"Loaded known faces: {set(self.known_names)}")

    def confirm_training(self, name):
        """
        Confirm and start the training process for a new face.

        Args:
            name (str): The name of the person being trained.
        """
        # Refereced and modified accordingly from YouTube video:
        # "Facial Recognition for Raspberry Pi with OpenCV and Python" by Core Electronics,
        # URL: https://www.youtube.com/watch?v=3TUlJrRJUeM, retrieved on 2025-04-01

        self.training_session_active = True
        self.pi.write(YELLOW_LED, 1)
        picam2 = None  # Initialize the camera variable
        try:
            # Step 1: Capture photos
            print(f"[INFO] Starting photo capture for {name}")

            folder = os.path.join(DATASET_DIR, name)
            os.makedirs(folder, exist_ok=True)

            picam2 = Picamera2()
            picam2.configure(
                picam2.create_preview_configuration(
                    main={"format": "XRGB8888", "size": (640, 480)}
                )
            )
            picam2.start()
            time.sleep(2)

            photo_count = 0
            while photo_count < 5:
                frame = picam2.capture_array()
                rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                face_locations = face_recognition.face_locations(rgb_frame)

                # Display the frame in a window
                cv2.imshow("Capturing Face", frame)
                cv2.waitKey(1)  # Refresh the window

                if face_locations:
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    filepath = os.path.join(folder, f"{timestamp}.jpg")
                    cv2.imwrite(filepath, frame)
                    print(f"[INFO] Saved photo {photo_count + 1}: {filepath}")
                    photo_count += 1
                    time.sleep(
                        1
                    )  # Add a delay between captures to ensure different frames

            print(
                f"[INFO] Finished capturing {photo_count} images for {name}.")

            # Close the camera after capturing photos
            picam2.stop()
            picam2.close()
            cv2.destroyAllWindows()

            # Step 2: Retrain model with all dataset images
            print("[INFO] Starting face encoding and model update...")
            imagePaths = list(paths.list_images(DATASET_DIR))

            for i, imagePath in enumerate(imagePaths):
                print(f"[INFO] Processing image {i + 1}/{len(imagePaths)}")
                label = imagePath.split(os.path.sep)[-2]
                image = cv2.imread(imagePath)
                rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

                boxes = face_recognition.face_locations(rgb, model="hog")
                encodings = face_recognition.face_encodings(rgb, boxes)

                for encoding in encodings:
                    self.known_encodings.append(encoding)
                    self.known_names.append(label)

            data = {"encodings": self.known_encodings,
                    "names": self.known_names}
            with open("encodings.pickle", "wb") as f:
                f.write(pickle.dumps(data))
            print("[INFO] Training complete. Encodings updated.")

            # Reload the known faces into memory
            self.load_known_faces()
            client.publish(
                TOPIC_ALERT, f"Face registration for {name} completed successfully."
            )
        except Exception as e:
            print(f"[ERROR] Failed training: {e}")
            client.publish(TOPIC_ALERT, f"Training failed for {name}: {e}")
        finally:
            if picam2:  # Ensure the camera is closed if it was initialized
                picam2.stop()
                picam2.close()
            cv2.destroyAllWindows()  # Close the OpenCV window
            self.training_session_active = False
            self.suppress_motion_detection = False
            self.pi.write(YELLOW_LED, 0)


class DoorController:
    def __init__(self, door, mqtt_client):
        """
        Initialize the DoorController with a SmartDoor instance and MQTT client.

        Args:
            door (SmartDoor): The SmartDoor instance to control.
            mqtt_client (mqtt.Client): The MQTT client for communication.
        """
        # Initialize DoorController with a SmartDoor instance and MQTT client
        self.door = door
        self.client = mqtt_client
        self.pending_unlock_name = None  # Name of the person awaiting unlock confirmation
        self.unlock_timer = None  # Timer for pending unlock requests
        self.processing_motion = False  # Flag to indicate if motion is being processed

    def cancel_unlock_request(self):
        """
        Cancel an unlock request if it times out.
        Notifies via MQTT about the timeout.
        """
        if self.pending_unlock_name:
            print(
                f"[INFO] Unlock request for {self.pending_unlock_name} timed out.")
            # Notify via MQTT that the unlock request timed out
            self.client.publish(
                TOPIC_ALERT, f"Unlock request for {self.pending_unlock_name} timed out."
            )
            self.pending_unlock_name = None  # Clear the pending unlock name

    def on_connect(self, client, userdata, flags, reason_code, properties=None):
        """
        Handle MQTT connection events.

        Args:
            client (mqtt.Client): The MQTT client instance.
            userdata: User-defined data passed to the callback.
            flags: Response flags sent by the broker.
            reason_code (int): The connection result code.
            properties (optional): MQTT v5 properties.
        """
        if reason_code == 0:
            print("Connected to MQTT broker.")
            client.subscribe(TOPIC_CONTROL)
        else:
            print("Failed to connect:", reason_code)

    def on_message(self, client, userdata, msg):
        """
        Handle incoming MQTT messages and perform actions based on the message.

        """
        message = msg.payload.decode()  # Decode the received message
        print(f"[INFO] Received MQTT message: {message}")

        if message == "open":
            # Handle the 'open' command to open the door
            print("[INFO] MQTT 'open' command received. Opening the door.")
            self.door.handle_door_opening()
        elif message == "confirm_register":
            # Handle confirmation for face registration
            if self.door.training_session_active:
                print("[INFO] Training already in progress. Ignoring confirm.")
            elif self.door.awaiting_training_name:
                self.door.confirm_training(self.door.awaiting_training_name)
            else:
                print("[WARN] No training session awaiting confirmation.")
                # Notify via MQTT if no training session is awaiting confirmation
                self.client.publish(
                    TOPIC_ALERT, "No training session awaiting confirmation."
                )
        elif message == "cancel_register":
            # Handle cancellation of face registration
            print("[INFO] Training canceled via app.")
            self.door.training_session_active = False
            self.door.awaiting_training_name = None
            self.door.suppress_motion_detection = False
            self.door.pi.write(YELLOW_LED, 0)
            print("[INFO] Face registration process canceled.")
            # Notify via MQTT that the face registration process was canceled
            self.client.publish(
                TOPIC_ALERT, "Face registration process canceled."
            )
        elif message == "open_confirmed" and self.pending_unlock_name:
            # Handle confirmation to open the door for a recognized face
            print(f"[INFO] Open confirmed for {self.pending_unlock_name}")
            self.door.handle_door_opening()
            self.pending_unlock_name = None  # Clear the pending unlock name
            # Cancel the unlock timer if it is still active
            if self.unlock_timer and self.unlock_timer.is_alive():
                self.unlock_timer.cancel()
        elif message == "deny_open":
            # Handle denial of an unlock request
            print("[INFO] Open request denied.")
            self.pending_unlock_name = None  # Clear the pending unlock name
            # Cancel the unlock timer if it is still active
            if self.unlock_timer and self.unlock_timer.is_alive():
                self.unlock_timer.cancel()
        else:
            # Handle unknown MQTT messages
            print(f"[WARN] Unknown MQTT message: {message}")

    def recognize_and_request_unlock(self):
        """
        Perform face recognition and request unlock confirmation via MQTT.
        Temporarily disables motion detection during the process.
        """
        # Referenced and modified from YouTube video:
        # "Facial Recognition for Raspberry Pi with OpenCV and Python" by Core Electronics,
        # URL: https://www.youtube.com/watch?v=3TUlJrRJUeM, retrieved on 2025-04-01

        picam2 = None  # Initialize the camera variable
        try:
            # Configure and start the camera
            picam2 = Picamera2()
            preview_config = picam2.create_preview_configuration(
                main={"format": "XRGB8888", "size": (640, 480)}
            )
            picam2.configure(preview_config)
            picam2.start()
            time.sleep(1)  # Allow the camera to stabilize

            start_time = time.time()  # Record the start time
            face_recognized = False  # Flag to indicate if a face is recognized
            recognized_name = "Unknown"  # Default name for unrecognized faces

            while True:
                # Capture a frame from the camera
                frame = picam2.capture_array()
                rgb_frame = cv2.cvtColor(
                    frame, cv2.COLOR_BGR2RGB)  # Convert to RGB
                face_locations = face_recognition.face_locations(
                    rgb_frame)  # Detect faces
                face_encodings = face_recognition.face_encodings(
                    rgb_frame, face_locations
                )  # Encode faces

                bgr_frame = cv2.cvtColor(
                    rgb_frame, cv2.COLOR_RGB2BGR)  # Convert back to BGR

                for (top, right, bottom, left), face_encoding in zip(
                    face_locations, face_encodings
                ):
                    # Compare the detected face with known encodings
                    matches = face_recognition.compare_faces(
                        self.door.known_encodings, face_encoding
                    )
                    face_distances = face_recognition.face_distance(
                        self.door.known_encodings, face_encoding
                    )
                    name = "Unknown"  # Default to "Unknown" if no match is found

                    if len(face_distances) > 0:
                        # Find the best match for the detected face
                        best_match_index = np.argmin(face_distances)
                        if matches[best_match_index]:
                            name = self.door.known_names[best_match_index]
                            face_recognized = True  # Mark face as recognized
                            recognized_name = name

                    # Draw a box around the face
                    cv2.rectangle(
                        bgr_frame, (left, top), (right, bottom), (0, 255, 0), 2
                    )
                    # Draw a label with the name of the recognized face
                    cv2.putText(
                        bgr_frame,
                        name,
                        (left, bottom + 20),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        (255, 255, 255),
                        2,
                    )

                # Display the resulting image
                cv2.imshow("Face Recognition", bgr_frame)

                # Exit the loop if a face is recognized
                if face_recognized:
                    print(
                        f"[INFO] Recognized {recognized_name}, requesting confirmation to unlock."
                    )
                    break

                # Press 'q' to exit the loop manually
                if cv2.waitKey(1) & 0xFF == ord("q"):
                    break

                # Exit after 10 seconds
                if time.time() - start_time > 10:
                    break
        finally:
            # Ensure the camera is stopped and resources are released
            if picam2:
                picam2.stop()
                picam2.close()
            cv2.destroyAllWindows()

        if face_recognized:
            # Notify via MQTT that a face was recognized and request confirmation
            self.door.suppress_motion_detection = True
            self.client.publish(
                TOPIC_ALERT,
                f"Recognized {recognized_name}. Awaiting confirmation to unlock.",
            )
            self.pending_unlock_name = recognized_name  # Set the pending unlock name
            # Start a timer to cancel the unlock request if not confirmed
            self.unlock_timer = threading.Timer(
                15.0, self.cancel_unlock_request)
            self.unlock_timer.start()
        else:
            # Notify via MQTT that an unknown face was detected
            print("[INFO] Unknown face detected.")
            self.client.publish(TOPIC_ALERT, "Unknown face detected.")


# Set up MQTT client
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
client.username_pw_set(USERNAME, PASSWORD)

door = SmartDoor(pi)
controller = DoorController(door, client)

client.on_connect = controller.on_connect
client.on_message = controller.on_message

client.connect(BROKER, PORT, 60)
client.loop_start()

# Initialize system with LED indicators
pi.write(RED_LED, 1)  # Door starts locked
pi.write(GREEN_LED, 0)
pi.write(YELLOW_LED, 0)

# Add startup delay to let sensors stabilize
print("[INFO] Starting smart door system...")
print("[INFO] Letting sensors stabilize...")
time.sleep(1)  # Wait for motion sensor to stabilize
print("[INFO] System ready - monitoring for motion")

# Flash LEDs to signal system is ready
pi.write(RED_LED, 0)
pi.write(YELLOW_LED, 1)
pi.write(GREEN_LED, 1)
time.sleep(0.2)
pi.write(RED_LED, 1)
pi.write(YELLOW_LED, 0)
pi.write(GREEN_LED, 0)

try:
    while True:
        if (
            not door.suppress_motion_detection
            and motion.motion_detected
            and not controller.processing_motion
        ):
            if door.locked:
                controller.processing_motion = True
                print("[INFO] Motion detected. Starting recognition...")
                controller.recognize_and_request_unlock()
                controller.processing_motion = False
        time.sleep(0.1)
except KeyboardInterrupt:
    print("\n[INFO] Exiting...")
    client.loop_stop()
    client.disconnect()
    pi.write(RED_LED, 0)
    pi.write(GREEN_LED, 0)
    pi.write(YELLOW_LED, 0)
    pi.stop()
